name: Build and Push Docker Images and Helm Chart

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  DOCKERHUB_REPO_BACKEND: idjohnson/dblogapp2-backend
  DOCKERHUB_REPO_FRONTEND: idjohnson/dblogapp2-frontend
  HELM_CHART_REPO: idjohnson/dblogapp2-chart

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_REPO_BACKEND }}:latest

      # Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_REPO_FRONTEND }}:latest

      # Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4

      # Package Helm chart
      - name: Package Helm chart
        run: |
          helm package dblogapp2-chart --destination packaged-chart

      # Log in to Helm OCI registry (Docker Hub)
      - name: Helm OCI login
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Push Helm chart to Docker Hub as OCI
      - name: Push Helm chart to Docker Hub OCI
        run: |
          CHART_VERSION=$(helm show chart dblogapp2-chart | grep '^version:' | awk '{print $2}')
          helm push packaged-chart/dblogapp2-${CHART_VERSION}.tgz oci://${{ env.REGISTRY }}/${{ env.HELM_CHART_REPO }}